current_profile: default
debounce_seconds: 5
rclone_path: dotfiles
rclone_remote: ustc_webdav
sync_interval_minutes: 10
ignores:
  - ".git/"
  - "__pycache__/"
  - "*.pyc"
  - ".DS_Store"
  - "fish_history"
  - "fish_variables.*"
  - "generated_completions/"
  - "dotdav.fish"
  - ".trash/"
