
debounce_seconds: 5
ignores:
- .git/
- __pycache__/
- '*.pyc'
- .DS_Store
- fish_history
- fish_variables.*
- generated_completions/
- dotdav.fish
- .trash/
rclone_path: dotfiles
rclone_remote: ustc_webdav
sync_interval_minutes: 10
