[project]
name = "dotdav"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.3",
    "watchdog>=6.0.0",
]

[project.scripts]
dotdav = "dotdav.main:main"
